# Site Settings
title: "Abby's Dev Notes on Power Platform"
description: >- 
  A collection of technical notes, tips & insights, and 'gotchas' from the Power Platform. Shared for the community and my future self.
# Technical Routing
baseurl: "/blog" # Matches your repository name for correct CSS loading
url: "https://abbykong.github.io" 
permalink: /:title/

# Professional Identity (Privacy Protected)
author:
  name: "Abby Kong"
  github_username: "abbykong"

# Theme Engine
remote_theme: pages-themes/slate@v0.2.0

# Build Settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed

show_downloads: false
